import _cython_3_1_4
import enum
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__test__: dict
add_data: _cython_3_1_4.cython_function_or_method
add_file: _cython_3_1_4.cython_function_or_method
complete: _cython_3_1_4.cython_function_or_method
create: _cython_3_1_4.cython_function_or_method
destroy: _cython_3_1_4.cython_function_or_method
get_error_log: _cython_3_1_4.cython_function_or_method
get_error_log_size: _cython_3_1_4.cython_function_or_method
get_info_log: _cython_3_1_4.cython_function_or_method
get_info_log_size: _cython_3_1_4.cython_function_or_method
get_linked_cubin: _cython_3_1_4.cython_function_or_method
get_linked_cubin_size: _cython_3_1_4.cython_function_or_method
get_linked_ptx: _cython_3_1_4.cython_function_or_method
get_linked_ptx_size: _cython_3_1_4.cython_function_or_method
version: _cython_3_1_4.cython_function_or_method

class InputType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ANY: ClassVar[InputType] = ...
    CUBIN: ClassVar[InputType] = ...
    FATBIN: ClassVar[InputType] = ...
    INDEX: ClassVar[InputType] = ...
    LIBRARY: ClassVar[InputType] = ...
    LTOIR: ClassVar[InputType] = ...
    NONE: ClassVar[InputType] = ...
    OBJECT: ClassVar[InputType] = ...
    PTX: ClassVar[InputType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class Result(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ERROR_ARCH_MISMATCH: ClassVar[Result] = ...
    ERROR_FINALIZE: ClassVar[Result] = ...
    ERROR_INCOMPATIBLE_OPTIONS: ClassVar[Result] = ...
    ERROR_INCORRECT_INPUT_TYPE: ClassVar[Result] = ...
    ERROR_INTERNAL: ClassVar[Result] = ...
    ERROR_INVALID_INPUT: ClassVar[Result] = ...
    ERROR_LTO_NOT_ENABLED: ClassVar[Result] = ...
    ERROR_MISSING_ARCH: ClassVar[Result] = ...
    ERROR_MISSING_FATBIN: ClassVar[Result] = ...
    ERROR_NULL_INPUT: ClassVar[Result] = ...
    ERROR_NVVM_COMPILE: ClassVar[Result] = ...
    ERROR_OUTDATED_LIBRARY: ClassVar[Result] = ...
    ERROR_PTX_COMPILE: ClassVar[Result] = ...
    ERROR_THREADPOOL: ClassVar[Result] = ...
    ERROR_UNRECOGNIZED_ARCH: ClassVar[Result] = ...
    ERROR_UNRECOGNIZED_INPUT: ClassVar[Result] = ...
    ERROR_UNRECOGNIZED_OPTION: ClassVar[Result] = ...
    ERROR_UNSUPPORTED_ARCH: ClassVar[Result] = ...
    SUCCESS: ClassVar[Result] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class nvJitLinkError(Exception):
    def __init__(self, status) -> Any: ...
    def __reduce__(self) -> Any: ...
