from cuda.core.experimental._device import Device as Device
from cuda.core.experimental._utils.cuda_utils import CUDAError as CUDAError, cast_to_3_tuple as cast_to_3_tuple, driver as driver, get_binding_version as get_binding_version, handle_return as handle_return
from dataclasses import dataclass

@dataclass
class LaunchConfig:
    grid: tuple | int = ...
    cluster: tuple | int = ...
    block: tuple | int = ...
    shmem_size: int | None = ...
    cooperative_launch: bool | None = ...
    def __post_init__(self) -> None: ...
