from _typeshed import Incomplete
from cuda.core.experimental._device import Device as Device
from cuda.core.experimental._linker import Linker as Linker, LinkerHandleT as LinkerHandleT, LinkerOptions as LinkerOptions
from cuda.core.experimental._module import ObjectCode as ObjectCode
from cuda.core.experimental._utils.clear_error_support import assert_type as assert_type
from cuda.core.experimental._utils.cuda_utils import check_or_create_options as check_or_create_options, driver as driver, get_binding_version as get_binding_version, handle_return as handle_return, is_nested_sequence as is_nested_sequence, is_sequence as is_sequence, nvrtc as nvrtc
from dataclasses import dataclass

@dataclass
class ProgramOptions:
    name: str | None = ...
    arch: str | None = ...
    relocatable_device_code: bool | None = ...
    extensible_whole_program: bool | None = ...
    debug: bool | None = ...
    lineinfo: bool | None = ...
    device_code_optimize: bool | None = ...
    ptxas_options: str | list[str] | tuple[str] | None = ...
    max_register_count: int | None = ...
    ftz: bool | None = ...
    prec_sqrt: bool | None = ...
    prec_div: bool | None = ...
    fma: bool | None = ...
    use_fast_math: bool | None = ...
    extra_device_vectorization: bool | None = ...
    link_time_optimization: bool | None = ...
    gen_opt_lto: bool | None = ...
    define_macro: str | tuple[str, str] | list[str | tuple[str, str]] | tuple[str | tuple[str, str]] | None = ...
    undefine_macro: str | list[str] | tuple[str] | None = ...
    include_path: str | list[str] | tuple[str] | None = ...
    pre_include: str | list[str] | tuple[str] | None = ...
    no_source_include: bool | None = ...
    std: str | None = ...
    builtin_move_forward: bool | None = ...
    builtin_initializer_list: bool | None = ...
    disable_warnings: bool | None = ...
    restrict: bool | None = ...
    device_as_default_execution_space: bool | None = ...
    device_int128: bool | None = ...
    optimization_info: str | None = ...
    no_display_error_number: bool | None = ...
    diag_error: int | list[int] | tuple[int] | None = ...
    diag_suppress: int | list[int] | tuple[int] | None = ...
    diag_warn: int | list[int] | tuple[int] | None = ...
    brief_diagnostics: bool | None = ...
    time: str | None = ...
    split_compile: int | None = ...
    fdevice_syntax_only: bool | None = ...
    minimal: bool | None = ...
    def __post_init__(self) -> None: ...

ProgramHandleT: Incomplete

class Program:
    class _MembersNeededForFinalize:
        handle: Incomplete
        backend: Incomplete
        def __init__(self, program_obj, handle, backend) -> None: ...
        def close(self) -> None: ...
    def __init__(self, code, code_type, options: ProgramOptions = None) -> None: ...
    def close(self) -> None: ...
    def compile(self, target_type, name_expressions=(), logs=None): ...
    @property
    def backend(self) -> str: ...
    @property
    def handle(self) -> ProgramHandleT: ...
