from cuda.core.experimental._device import Device as Device
from cuda.core.experimental._utils.cuda_utils import driver as driver, handle_return as handle_return, runtime as runtime

class System:
    def __new__(cls): ...
    def __init__(self) -> None: ...
    @property
    def driver_version(self) -> tuple[int, int]: ...
    @property
    def num_devices(self) -> int: ...
    @property
    def devices(self) -> tuple: ...
